### ISSUE TITLE
Google API 

### ISSUE THREAD

**Issue by hockeyservices** [tobiasbueschel/virtual-reality-tour#6]
Hi, thanks for the this project. After installing I have one issue: Google Maps API error: MissingKeyMapError
Have you an idea ?

kind regards
Pat

**Comment by hockeyservices** [comment]
sorry solved - Add API Key to index.html script

**Comment by tobiasbueschel** [comment]
Hey @hockeyservices :wave: 

Glad to hear you got it solved! I'll close this issue then :)
